name: Build and Auto-Update Build Version
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "XDRInternals/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Prerequisites
        run: ./build/vsts-prerequisites.ps1
        shell: pwsh
      - name: Validate
        run: ./build/vsts-validate.ps1
        shell: pwsh
      - name: Build
        run: ./build/vsts-build.ps1 -ApiKey $env:APIKEY -AutoVersion
        shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
